title: HIL Wiki
description: Knowledge base of the items used at the HIL
theme: just-the-docs

url: https://herculesinnovationlab.github.io/Wiki

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

  color_scheme: dark
